.\"
.\" Copyright (c) 2020 Scott Bennett <scottb@fastmail.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd March 19, 2020
.Dt Y86_OBJ_CODE 7
.Os
.Sh NAME
.Nm y86_obj_code
.Nd y86 object code reference
.Sh DESCRIPTION
.Sy y86 object code
is represented by ASCII text files ending in a
.Em \.yo
extension.
Each line in the program file is either a
.Sy comment record
or a
.Sy data record .
.Pp
A
.Sy comment record
is of the form:
.Bd -literal
                      | comment here

.Ed
where columns 0\(en21 contain space characters
.Pq Sq " "
and column 22 contains a pipe character
.Pq Sq | .
Any characters beyond column 22 are considered part of a comment and are
ignored.
.Pp
A
.Sy data record
is of the form:
.Bd -literal
  0x042: 0f000000     |

.Ed
where columns 0, 1, 8, and 21 (at least) contain space characters, columns 2\(en7
contain an address, columns 9 up to 20 contain zero to six bytes of data, and
column 22 contains a pipe character
.Pq Sq | .
Characters beyond column 22 are considered comment characters and are ignored.
The address in columns 2\(en7 is a hex address.
Both upper a lower case characters are accepted.
This address indicates the starting byte address of the first byte in memory
where the data (in columns 9 up to 20) is to be stored.
.Pp
.Sh EXAMPLES
.\" Add a few comment and data record examples.
.Bd -literal
  0x000:              |    .pos 0

.Ed
The beginning point of a program.
.Bd -literal
  0x014:              |    .align 4
  0x014: 0d000000     | array: .long 0xd

.Ed
Declare the beginning of an array.
.Sh SEE ALSO
.Xr yess 1
