.\"
.\"Copyright (c) 2020 Scott Bennett <scottb@fastmail.com>
.\"
.Dd $Mdocdate$
.Dt Y86_OBJ_CODE 7
.Os
.Sh NAME
.Nm y86_obj_code
.Nd y86 object code reference
.Sh DESCRIPTION
.Sy y86 object code
is represented by ASCII text files ending in a
.Em \.yo
extension.
Each line in the program file is either a
.Sy comment record
or a
.Sy data record .
.Pp
A
.Sy comment record
is of the form:
.Bd -literal -compact
                      | comment here
.Ed
where columns 0-21 contain space characters
(
.Sq 
)
and column 22 contains a pipe character (
.Sq |
) .
Any characters beyond column 22 are considered part of a
comment and are ignored.
.Pp

.Sh SEE ALSO
.Xr yess 1
