.\"
.\" Copyright (c) 2020 Scott Bennett <scottb@fastmail.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd July 21, 2020
.Dt YESS 1
.Os
.Sh NAME
.Nm yess
.Nd y86 simulator
.Sh SYNOPSIS
.Nm yess
.Op Fl duv
.Fl f Ar prog.yo
.Sh DESCRIPTION
The
.Nm
program simulates the execution of y86 object code.
Object code must be placed in a file ending with a
.Em .yo
extension.
This program file is a regular ASCII file, not a binary.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl d
Produce debug messages.
.Nm
will write debug information to stderr.
.It Fl u
Print usage information and exit.
.It Fl v
Verbose mode.
.Nm
will write more information to stderr (but not as much as
.Fl d
mode).
.El
.Sh SEE ALSO
.Xr y86_obj_code 7
.Sh AUTHORS
This program was written by
.An Scott Bennett
and
.An Alex Svarda .
